name: Add my node
description: Send us a node you wrote and want us to add to Coollab
title: "[New node] "
labels: ["enhancement"]
body:
  - type: input
    id: name
    attributes:
      label: Name of your node
      description: (We might change it to make it match Coollab's conventions)

  - type: textarea
    id: was-is-your-node
    attributes:
      label: What does your node do?
      description: A very brief description
    validations:
      required: false
      
  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I agree for my node to be added to Coollab for all of its users.
          required: true

  - type: textarea
    id: code
    attributes:
      label: Code
      description: Please copy-paste the entirety of your .clbnode file here.
      render: GLSL
    validations:
      required: true
