name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, how can we reproduce the bug? Does it happen all the time or is it random?
    validations:
      required: true
  - type: textarea
    id: project-file
    attributes:
      label: Project file
      description: Please share your project which is causing the problem, so that we can easily reproduce it
    validations:
      required: false
  - type: textarea
    id: log-file
    attributes:
      label: Log file
      description: "[Use this short tutorial](https://coollab-art.com/Tutorials/Miscellaneous/Log%20File) to find the \"LOG Coollab.txt\" file, and drop it here"
    validations:
      required: true
