name: Feature Suggestion
description: Tell us how we could improve Coollab
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: what-is-your-suggestion
    attributes:
      label: What is your suggestion?
      description: Tell us how we could improve Coollab
    validations:
      required: true
