name: Create release executables

on: workflow_dispatch

env:
  TARGET: CoolLab


jobs:
#-----------------------------------------------------------------------------------------------
  Windows_Clang_Release:
    name: Windows Clang Release
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
          
    - name: Test1
      run: ls

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -T ClangCL

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Release --target ${{env.TARGET}}

    - name: Zip files
      uses: vimtor/action-zip@v1
        with:
          files: bin\Release\
          dest: CoolLab-Windows.zip

    - name: Test2
      run: ls
    - name: Test3
      run: |
            cd ${{github.workspace}}/bin
            ls

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}\CoolLab-Windows.zip
#-----------------------------------------------------------------------------------------------
  Linux_Clang_Release:
    name: Linux Clang Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update apt-get
      run: sudo apt-get update -y

    - name: Install glfw dependencies
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev build-essential libgtk-3-dev    

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}

    - name: Zip files
      run: |
            cd ${{github.workspace}}/bin
            mv Release CoolLab-Linux
            tar -cvzf CoolLab-Linux.tar.gz ./CoolLab-Linux
            
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/bin/CoolLab-Linux.tar.gz

#-----------------------------------------------------------------------------------------------
  MacOS_Clang_Release:
    name: MacOS Clang Release
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}
      
    - name: Zip files
      run: |
            cd ${{github.workspace}}/bin
            mv Release CoolLab-MacOS
            zip -r CoolLab-MacOS.zip ./CoolLab-MacOS

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/bin/CoolLab-MacOS.zip

