name: Create release executables

on: workflow_dispatch

env:
  TARGET: Coollab

jobs:
  #-----------------------------------------------------------------------------------------------
  Windows_Clang_Release:
    name: Windows Clang Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -T ClangCL -D COOLLAB_REQUIRE_ALL_FEATURES=ON -D CPACK_GENERATOR=NSIS

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config Release --target ${{env.TARGET}}

      - name: Create installer
        run: |
          cd ${{github.workspace}}\build
          cpack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Coollab-Windows.exe

  #-----------------------------------------------------------------------------------------------
  Linux_GCC_Release:
    name: Linux GCC Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update apt-get
        run: sudo apt-get update -y

      - name: Install glfw dependencies
        run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev build-essential libgtk-3-dev

      - name: Install OpenSSL
        run: sudo apt-get install libssl-dev

      - name: Install MIDI dependencies
        run: sudo apt install libasound2-dev

      - name: Install Audio dependencies
        run: sudo apt install libpulse-dev libasound2-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D COOLLAB_REQUIRE_ALL_FEATURES=ON -D CPACK_GENERATOR=STGZ

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}

      - name: Create installer
        run: |
          cd ${{github.workspace}}/build
          cpack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/build/Coollab-Linux.sh

  #-----------------------------------------------------------------------------------------------
  MacOS_Clang_Release:
    name: MacOS Clang Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -D COOLLAB_REQUIRE_ALL_FEATURES=ON -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl -D OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -D CPACK_GENERATOR=Bundle

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}

      - name: Create installer
        run: |
          cd ${{github.workspace}}/build
          cpack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/build/Coollab-Mac.dmg
